$(document).ready(function(){
	//进入页面检测是否已登录----------------------------
	var sch = true;
		$.ajax({
			url:"LoginController",
			type:"post",
			data:{"sw":"init","ts":"f"},
			success:function(msg){
				if(msg=="0"){
					$(location).attr("href","login.jsp");
				}else{
					$("b").empty();
					$("b").append("用户已登录："+msg);
				}
			}
		});
	//安全退出----------------------------
	$("p").click(function(){
		$.ajax({
			url:"LoginController",
			type:"post",
			data:{"sw":"init","ts":"e"},
			success:function(msg){			
					$(location).attr("href","login.jsp");				
			}
		});
	});
});